name: example
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  example:
    strategy:
      max-parallel: 20
      matrix:
        os: [ ubuntu-latest,windows-latest,macos-latest ]
        java: [ 8,11 ]
        node: [ 14,16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: set java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: echo
        run: |
          java -version
          node -v
          echo Hello World!
