name: example  # 定义工作流名称
on:  # 触发方式
  push:  # 触发push时开始执行
    branches:  # 指定分支
      - master
  schedule:  # 定时触发
    - cron: "0 1 * * *"  # 定时任务，类似linux-cron
  workflow_dispatch:  # web上手动触发
jobs:  # 作业
  example:  # 作业名称
    strategy:  # 并发策略
      max-parallel: 20  # 并发数量
      matrix:  # 并发矩阵，自定义
        os: [ ubuntu-latest,windows-latest,macos-latest ]  # 操作系统
        java: [ 8,11 ]  # java版本
        node: [ 14,16 ]  # node版本
    runs-on: ${{ matrix.os }}  # 运行的操作系统
    steps:  # 步骤
      - name: set java  # 安装一个java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: set node  # 安装一个node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: echo  # 输出java版本，node版本，你好，世界！
        run: |
          java -version
          node -v
          echo Hello World!
